# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wppmessage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# Flávio Oliveira - 2021 - Versão 1.0
# https://github.com/oliveiradeflavio

import pywhatkit as kit

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    #stylesheet frameok mensagem ok ou error
    stylePopupError = ("background-color: rgb(252, 2, 20); border-radius: 10px;")
    stylePopupOk = ("background-color: rgb(0, 25, 123); border-radius: 10px;")

    #stylesheet
    styleLineEditOk = ("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border:  rgb(45,45,45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(238, 238, 238);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(45,45,45);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(55,55,55);\n"
"}")

    stylePlainTextOk = ("QPlainTextEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border:  rgb(45,45,45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(238, 238, 238);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPlainTextEdit:hover{\n"
"    border: 2px solid rgb(45,45,45);\n"
"}\n"
"QPlainTextEdit:focus{\n"
"    border: 2px solid rgb(55,55,55);\n"
"}")

    stylePlainTextError = ("QPlainTextEdit{\n"
"    border: 2px solid rgb(255,85,127);\n"
"    border:  rgb(255,85,127);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(255,85,127);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPlainTextEdit:hover{\n"
"    border: 2px solid rgb(255,85,127);\n"
"}\n"
"QPlainTextEdit:focus{\n"
"    border: 2px solid rgb(255,85,127);\n"
"}")


    styleLineEditError = ("QLineEdit{\n"
"    border: 2px solid rgb(255,85,127);\n"
"    border:  rgb(255,85,127);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(255,85,127);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(255,85,127);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255,85,127);\n"
"}")

    #validando campos
    def checandoCampos(self):
        textNumero = ""
        textMensagem = ""
        textHorario = ""
        
        #limparcampos
        def limpaCampos(self):
            self.lineEdit_Numero.setText("")
            self.plainTextEdit_Mensagem.setPlainText("")
            self.lineEdit_Horario.setText("")

        def showMessage(message):
            self.frame_error.show()
            self.label_error.setText(message)

        #checar número
        if not self.lineEdit_Numero.text():
            textNumero = "Número vazio "
            self.lineEdit_Numero.setStyleSheet(self.styleLineEditError)
        else:
            textNumero = ""
            self.lineEdit_Numero.setStyleSheet(self.styleLineEditOk)

        #checar MENSAGEM
        if not self.plainTextEdit_Mensagem.toPlainText():
            textMensagem = "Mensagem vazio"
            self.plainTextEdit_Mensagem.setStyleSheet(self.stylePlainTextError)
        else:
            textMensagem = ""
            self.plainTextEdit_Mensagem.setStyleSheet(self.stylePlainTextOk)

        #checar horário
        if not self.lineEdit_Horario.text():
            textHorario = " Horário vazio"
            self.lineEdit_Horario.setStyleSheet(self.styleLineEditError)
        else:
            textHorario = ""
            self.lineEdit_Horario.setStyleSheet(self.styleLineEditOk)

        #checando campos
        if textNumero + textMensagem + textHorario != "":
            text = textNumero + textMensagem + textHorario
            showMessage(text)
            self.frame_error.setStyleSheet(self.stylePopupError)
        else:
            numero = "+55" + self.lineEdit_Numero.text()
            mensagem = self.plainTextEdit_Mensagem.toPlainText()
            horario = self.lineEdit_Horario.text()

            #magia, o comando sendwhatmsg precisa de horário em int. Então estou fatiando as string para que eu possa tratar
            #quando o usuário digita o minuto em 0. Exemplo: 21:01, esse 01 preciso tratar e remover o 0 (zero).
            h = horario[0:2]
            m = horario[3:5]

            if int(m[0]) == 0:
                m = horario[4]
                kit.sendwhatmsg(numero, mensagem, int(h),int(m),3)
                showMessage("Mensagem Enviada")
                self.frame_error.setStyleSheet(self.stylePopupOk)
                limpaCampos(self)
             
            else:
                kit.sendwhatmsg(numero, mensagem, int(h),int(m),3)
                showMessage("Mensagem Enviada")
                self.frame_error.setStyleSheet(self.stylePopupOk)
                limpaCampos(self)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setStyleSheet("background-color: rgb(41,175,135);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_error = QtWidgets.QFrame(self.top_bar)
        self.frame_error.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_error.setStyleSheet(self.stylePopupError)
        self.frame_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.pushButton_closepopup = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_closepopup.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_closepopup.setStyleSheet("QPushButton{\n"
"    border-radius: 5px\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50,50,50);\n"
"    color: rgb(200,200,200);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35,35,35);\n"
"    color: rgb(200,200,200);\n"
"}")
        self.pushButton_closepopup.setObjectName("pushButton_closepopup")
        self.horizontalLayout_3.addWidget(self.pushButton_closepopup)
        self.horizontalLayout_2.addWidget(self.frame_error)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_area = QtWidgets.QFrame(self.content)
        self.login_area.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.label_Agende = QtWidgets.QLabel(self.login_area)
        self.label_Agende.setGeometry(QtCore.QRect(60, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(13)
        self.label_Agende.setFont(font)
        self.label_Agende.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Agende.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_Agende.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Agende.setObjectName("label_Agende")
        self.lineEdit_Numero = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_Numero.setGeometry(QtCore.QRect(70, 100, 321, 50))
        self.lineEdit_Numero.setStyleSheet(self.styleLineEditOk)
        self.lineEdit_Numero.setMaxLength(11)
        self.lineEdit_Numero.setObjectName("lineEdit_Numero")


#
#         self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.login_area)
#         self.dateTimeEdit.setGeometry(QtCore.QRect(70, 400, 321, 51))
#         self.dateTimeEdit.setStyleSheet("QDateTimeEdit{\n"
# "    border: 2px solid rgb(45,45,45);\n"
# "    border: rgb(92, 147, 30);\n"
# "    border-radius: 10px;\n"
# "    padding: 15px;\n"
# "    background-color: rgb(238, 238, 238);\n"
# "    color: rgb(0, 0, 0);\n"
# "}\n"
# "QDateTimeEdit:hover{\n"
# "    border: 2px solid rgb(55,55,55);\n"
# "}\n"
# "QDateTimeEdit:focus{\n"
# "    border: 2px solid rgb(55,55,55);\n"
# "}")
#         self.dateTimeEdit.setObjectName("dateTimeEdit")

        self.lineEdit_Horario = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_Horario.setGeometry(QtCore.QRect(70, 400, 321, 51))
        self.lineEdit_Horario.setStyleSheet(self.styleLineEditOk)

        self.lineEdit_Horario.setMaxLength(5)
        self.lineEdit_Horario.setObjectName("lineEdit_Horario")

        self.plainTextEdit_Mensagem = QtWidgets.QPlainTextEdit(self.login_area)
        self.plainTextEdit_Mensagem.setGeometry(QtCore.QRect(70, 160, 321, 221))
        self.plainTextEdit_Mensagem.setStyleSheet(self.stylePlainTextOk)
        self.plainTextEdit_Mensagem.setObjectName("plainTextEdit_Mensagem")
        self.pushButton_Enviar = QtWidgets.QPushButton(self.login_area)
        self.pushButton_Enviar.setGeometry(QtCore.QRect(70, 480, 331, 51))
        self.pushButton_Enviar.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border: rgb(45,45,45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(41,175,135);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 3px solid rgb(55,55,55);\n"
"}\n"
"")
        self.pushButton_Enviar.setObjectName("pushButton_Enviar")
        self.label_Agende_2 = QtWidgets.QLabel(self.login_area)
        self.label_Agende_2.setGeometry(QtCore.QRect(70, 50, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(10)
        self.label_Agende_2.setFont(font)
        self.label_Agende_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Agende_2.setStyleSheet("color: rgb(209, 209, 209);")
        self.label_Agende_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Agende_2.setObjectName("label_Agende_2")
        self.horizontalLayout.addWidget(self.login_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_flavio = QtWidgets.QLabel(self.bottom)
        self.label_flavio.setMinimumSize(QtCore.QSize(0, 10))
        self.label_flavio.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.label_flavio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_flavio.setObjectName("label_flavio")
        self.verticalLayout_2.addWidget(self.label_flavio)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)


        #button fechar do frame error, ocultado o frame_error
        self.pushButton_closepopup.clicked.connect(lambda: self.frame_error.hide())

        #ocultando frame Error
        self.frame_error.hide()

        #botão enviar MENSAGEM
        self.pushButton_Enviar.clicked.connect(self.checandoCampos)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WPP Message"))
        self.label_error.setText(_translate("MainWindow", "Error"))
        self.pushButton_closepopup.setText(_translate("MainWindow", "X"))
        self.label_Agende.setText(_translate("MainWindow", "WPPMESSAGE"))
        self.lineEdit_Numero.setInputMask(_translate("MainWindow", "00000000009"))
        self.lineEdit_Numero.setPlaceholderText(_translate("MainWindow", "DDD+Número"))
        self.plainTextEdit_Mensagem.setPlaceholderText(_translate("MainWindow", "Digite sua mensagem ..."))
        self.lineEdit_Horario.setInputMask(_translate("MainWindow", "00:09"))
        self.lineEdit_Horario.setPlaceholderText(_translate("MainWindow", "Horário: 00:00"))
        self.pushButton_Enviar.setText(_translate("MainWindow", "ENVIAR MENSAGEM"))
        self.label_Agende_2.setText(_translate("MainWindow", "Agende o envio de mensagem para o WhatsApp"))
        self.label_flavio.setText(_translate("MainWindow", "Flávio Oliveira"))
import wppmessage_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
